# config.py
# Functionality: Global configuration file containing model identifiers, training hyperparameters,
# API credentials (with environment variable support), reward parameters, and paths.

import os

# --- General Config ---
PROJECT_NAME = "llm-prompt-orchestrator"
SEED = 42

# --- Orchestrator Model Config ---
# We use 'distilgpt2' as the default small model suitable for local training on a 6GB VRAM GPU.
# You can upgrade this to 'gpt2' or larger models (e.g., 'Qwen/Qwen2.5-1.5B-Instruct') if GPU permits.
ORCHESTRATOR_MODEL_NAME = "distilgpt2" 
MAX_PROMPT_LEN = 128  # Maximum length of the mutated prompt generated by orchestrator

# --- Target LLM Config ---
# Support Groq / OpenAI or local Mock mode.
# By default, runs in MOCK mode to allow offline testing and pipeline validation.
USE_MOCK_TARGET = True
TARGET_PROVIDER = "mock"  # "mock", "groq", or "openai"
TARGET_MODEL_NAME = "llama3-8b-8192"  # or "gpt-4o-mini"
TARGET_API_KEY = os.getenv("TARGET_API_KEY", "")

# --- Training Hyperparameters ---
SFT_EPOCHS = 3
SFT_BATCH_SIZE = 4
SFT_LR = 5e-5

RL_EPOCHS = 5
RL_BATCH_SIZE = 4
RL_LR = 1e-5
RL_GAMMA = 0.99
RL_BETA = 0.01  # Entropy coefficient for exploration

# --- Task & Reward Configurations ---
# Task types: "json_format" or "token_reduction"
ACTIVE_TASK = "json_format" 

# Reward weights
REWARD_TASK_WEIGHT = 0.7       # Weight for formatting / correctness accuracy
REWARD_TOKEN_WEIGHT = 0.3      # Weight for token efficiency penalty

# Token penalty parameter: penalty is scaled by this factor (lower generated prompt length = higher reward)
TOKEN_PENALTY_SCALE = 0.005    # Penalty = TOKEN_PENALTY_SCALE * prompt_token_length

# --- Logging & Save Paths ---
MODEL_SAVE_DIR = "./models"
DATA_DIR = "./data"
LOG_DIR = "./logs"
WANDB_API_KEY = os.getenv("WANDB_API_KEY", "")
