# src/environment.py
# Functionality: Defines PromptOptimizationEnv which orchestrates the state transitions
# of the RL loop: generating mutated prompts, calling the Target LLM, and returning rewards.

from src.target_llm import TargetLLMClient
from src.reward import calculate_total_reward

class PromptOptimizationEnv:
    def __init__(self):
        self.target_llm = TargetLLMClient()

    def step(self, agent, raw_query: str, temperature: float = 0.7) -> dict:
        """
        Executes a single environment step:
        1. Agent generates a mutated prompt (Action) from a raw query (Observation).
        2. Mutated prompt is sent to the Target LLM.
        3. Response is evaluated to calculate the reward.
        
        Returns a dictionary containing:
            - raw_query: original input query
            - optimized_prompt: mutated prompt generated by orchestrator
            - target_response: final output from Target LLM
            - reward: computed scalar reward
            - prompt_token_len: length of generated prompt (action length)
        """
        # 1. Action: Generate optimized prompt
        optimized_prompt, prompt_token_len = agent.generate(raw_query, temperature=temperature)
        
        # 2. Transition: Feed optimized prompt to Target LLM
        target_response = self.target_llm.generate(optimized_prompt)
        
        # 3. Reward: Evaluate Target LLM output and token cost
        reward = calculate_total_reward(target_response, prompt_token_len)
        
        return {
            "raw_query": raw_query,
            "optimized_prompt": optimized_prompt,
            "target_response": target_response,
            "reward": reward,
            "prompt_token_len": prompt_token_len
        }
